INSERT INTO Accounts("FIRST_NAME", "SECOND_NAME", "ACCOUNT_NUM") VALUES('John','Doe','1234');
INSERT INTO Accounts("FIRST_NAME", "SECOND_NAME", "ACCOUNT_NUM") VALUES('Jane','Doe','1235');
INSERT INTO Accounts("FIRST_NAME", "SECOND_NAME", "ACCOUNT_NUM") VALUES('Jim','Taylor','1236');
